"""
Write a honcho Procfile with one collector process per ACM hub.

    data-layer/.venv/bin/python data-layer/scripts/gen_procfile_hubs.py [--base-port 18010] > Procfile.hubs

Reads the fleet config (ODL_CONFIG, relative to data-layer/) through the same
loader the collector uses, so the hub names are exactly the ones the
collector will accept in COLLECT_HUBS. Each process owns one hub
(COLLECT_HUBS=<hub>), listens on base-port + index, and shares REDIS_URL,
ODL_MANIFEST and the other settings from .env. The dashboard and the MCP
server should point at the first port (every process serves the whole
fleet's API from the shared Redis). Shard 0 semantics do not apply: each
process is its own fleet slice and does its own end-of-sweep housekeeping
for the clusters it owns.
"""
import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
sys.path.insert(0, ROOT)
os.environ.setdefault("ODL_MANIFEST", os.path.join(ROOT, "config", "ocp-api-manifest.yaml"))

from app.config_loader import load_config  # noqa: E402
from app.settings import settings  # noqa: E402


def slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_") or "hub"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--base-port", type=int, default=int(os.environ.get("HUB_BASE_PORT", "18010")))
    ap.add_argument("--workers", type=int, default=int(os.environ.get("COLLECT_WORKERS", "16")),
                    help="COLLECT_WORKERS per hub process")
    args = ap.parse_args()
    cfg = load_config(settings.config_path)
    if not cfg.hubs:
        print(f"no hubs: in {settings.config_path}", file=sys.stderr)
        return 2
    print(f"# Generated by scripts/gen_procfile_hubs.py from {settings.config_path}: one collector per hub.")
    print("# Regenerate after editing the hub list. Run with: make local-hubs")
    for i, hub in enumerate(cfg.hubs):
        port = args.base_port + i
        env = " ".join([
            f"COLLECT_HUBS={hub.name}",
            f"COLLECT_WORKERS=${{COLLECT_WORKERS:-{args.workers}}}",
            "REDIS_URL=${REDIS_URL:-redis://localhost:${ODL_REDIS_PORT:-16379}/0}",
            "ODL_MANIFEST=${ODL_MANIFEST:-config/ocp-api-manifest.fleet.yaml}",
            "ODL_CONFIG=${ODL_CONFIG:-config/acm.yaml}",
        ])
        print(f"{slug(hub.name)}: sh -c 'cd data-layer && {env} "
              f"exec .venv/bin/uvicorn app.main:app --host 127.0.0.1 --port {port}'")
    first = args.base_port
    print(f"ui: sh -c 'cd dashboard && VITE_PROXY_TARGET=http://localhost:{first} "
          "VITE_PATCHING_TARGET=http://localhost:${ODL_PATCHING_PORT:-18010} "
          "PORT=${DEV_UI_PORT:-5174} exec npm run dev'")
    print(f"mcp: sh -c 'cd mcp-server && MCP_API_BASE=http://localhost:{first} MCP_TRANSPORT=streamable-http "
          f"MCP_HOST=127.0.0.1 MCP_PORT=${{DEV_MCP_PORT:-18082}} exec .venv/bin/python server.py'")
    return 0


if __name__ == "__main__":
    sys.exit(main())
