"""
The committed OpenAPI document has to be the one the app actually serves.

`data-layer/openapi.json` is generated by `scripts/export_openapi.py` and is the
input to the dashboard's `npm run api:types` (ADR-0005). A committed document is
only worth having if it cannot drift, so the check lives here: add a route, or
change a query parameter, without re-running the script and this fails naming
the script to run.
"""
import json
import os
import sys

from scripts import export_openapi

COMMITTED = export_openapi.DEFAULT_OUTPUT


def _check(path: str) -> int:
    """`main()` in --check mode, which is the form CI would call."""
    argv = sys.argv
    sys.argv = ["export_openapi.py", "--check", "-o", path]
    try:
        return export_openapi.main()
    finally:
        sys.argv = argv


def test_committed_document_matches_the_app():
    assert os.path.exists(COMMITTED), (
        "data-layer/openapi.json is missing: run .venv/bin/python scripts/export_openapi.py")
    with open(COMMITTED, encoding="utf-8") as fh:
        committed = fh.read()
    assert committed == export_openapi.render(export_openapi.document()), (
        "data-layer/openapi.json is out of date: run "
        ".venv/bin/python scripts/export_openapi.py and commit the result")


def test_check_mode_answers_the_same_question(tmp_path):
    stale = tmp_path / "openapi.json"
    stale.write_text("{}\n", encoding="utf-8")
    assert _check(str(stale)) == 1
    assert _check(str(tmp_path / "never-written.json")) == 1
    assert _check(COMMITTED) == 0


def test_document_covers_the_routes_the_dashboard_calls():
    """A spot check that the export is the real document rather than a stub:
    the paths the dashboard's fetch helpers are built on are all in it."""
    paths = export_openapi.document()["paths"]
    for path in ("/api/health/overview", "/api/clusters", "/api/clusters/{name}",
                 "/api/blast-radius", "/api/insights/summary", "/api/query/sql",
                 "/api/dashboards/{dashboard_id}/run", "/api/agent", "/api/manifest",
                 "/api/metrics/capacity", "/api/collector/timings"):
        assert path in paths, f"{path} is missing from the exported document"

    # The generated types are only useful if the parameters come with them.
    assert any(p["name"] == "group_by"
               for p in paths["/api/metrics/capacity"]["get"]["parameters"])


def test_render_is_stable():
    """Two renders of the same document are byte-identical, which is what makes
    the committed file diffable."""
    doc = export_openapi.document()
    assert export_openapi.render(doc) == export_openapi.render(json.loads(json.dumps(doc)))
